# syntax=docker/dockerfile:1
services:
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/develop-colombo-clara-sponsor-erosion-6500
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /srv/neo4j/data:/data/:rw
    restart: always
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
