###

GET http://localhost:8080/api/vehicles

###

GET http://localhost:8080/api/people


###

POST http://localhost:8080/api/vehicles
Content-Type: application/json

{
  "id": "test123",
  "type": "CAR"
}

###

POST http://localhost:8080/api/people
Content-Type: application/json

"username"

###

GET http://localhost:8080/api/people/porterjason

###

GET http://localhost:8080/api/vehicles/3610afde-2bad-4045-a642-cfd2f5edb8d2


###


PUT http://localhost:8080/api/vehicles/d4c9316b-a5cc-41d1-8823-a2f4ea5b2b88
Content-Type: application/json

{
  "battery": 22.5,
  "latitude": 85.3,
  "longitude": 100.5,
  "status": "IN_USE"
}

###

POST http://localhost:8080/api/people/porterjason/ride
Content-Type: application/json

{
  "startingLatitude": 0,
  "startingLongitude": 0,
  "startingTime": "2007-12-03T10:15:30",
  "vehicle": {
    "id": "63f501bf-5592-4d7f-86de-6b32e6364e6b"
  }
}

###
POST http://localhost:8080/api/people/porterjason/recommend
Content-Type: application/json

{
  "startingLocation": {
    "latitude": 41.1227,
    "longitude": 29.0726
  },
  "endingLocation": {
    "latitude": 3.85,
    "longitude": 37.0
  }
}

###

POST http://localhost:8080/api/locations
Content-Type: application/json

{
  "latitude": 41.0429,
  "longitude": 29.029
}
